const ADD_COMMENT = "ADD_COMMENT";
const UPDATE_COMMENT = "UPDATE_COMMENT";
const DELETE_COMMENT = "DELETE_COMMENT";
const GET_COMMENTS = "GET_COMMENTS";

export { ADD_COMMENT, UPDATE_COMMENT, DELETE_COMMENT, GET_COMMENTS };
