const GET_PHOTOS = "GET_PHOTOS";
const GET_PHOTO_BY_ID = "GET_PHOTO_BY_ID";
const UPLOAD_PHOTO = "UPLOAD_PHOTO";
const GET_PHOTOS_BY_USER_ID = "GET_PHOTOS_BY_USER_ID";
const DELETE_PHOTO = "DELETE_PHOTO";
const UPDATE_LIKE_STATUS = "UPDATE_LIKE_STATUS";

export {
  GET_PHOTOS,
  GET_PHOTO_BY_ID,
  UPLOAD_PHOTO,
  GET_PHOTOS_BY_USER_ID,
  DELETE_PHOTO,
  UPDATE_LIKE_STATUS
};
